### ISSUE TITLE
[Review] Readme

### ISSUE THREAD

**Issue by NicolasGlassey** [dosseggegw1/AMT_projet#55]
# Readme (Evaluation 4 sur 5)

* Le document ne semble pas avoir été mis à jour. Des paragraphes sont vides (version automatique).
* Le build fonctionne sans problème (Testé sous Intellij qui ajoute automatiquement Hibernate Framework + JPA Bundle)
* En suivant le document, aucun test ne passe. Ce qui n'est pas étonnant car rien n'a été fait pour le mise en place de la base de données.

* Le projet contient un répertoire sql
    * un script "init" est disponbile mais il est partiellement commenté et génère une erreur lors de son exécution (il s'agit de la ligne dans laquel vous autoriser l'accès root depuis n'importe quelle source !!!)
    * le second script "AMT_SQL.sql" donne de meilleurs résultats et créer un modèle plus complet.
* L'utilisateur sql est identifié dans le fichier "hibernate. Root pour le user et le pwd sont nécessaires !!!
* Le script de création d'utilisateur pourrait être de ce genre (même si les droits de suppression sont nécessaires pour faire passer les tests, je vous conseille de revoir votre approche) :
```
CREATE USER 'shopels'@'localhost' IDENTIFIED BY '1234';
GRANT USAGE ON *.amt_sql TO 'shopels'@'localhost';
GRANT SELECT, ALTER, CREATE, DROP, INSERT, UPDATE, EXECUTE, SHOW VIEW, INDEX  ON `%`.* TO 'shopels'@'localhost';
FLUSH PRIVILEGES;
```

* Suite à cela la séquence de test a pu être lancée. Mes retours concernant les tests dans une issue spécifique à cela.

* Tentative de lancement de l'application après avoir configuré Tomcat dans Intellij. Le server se lance mais le déploiement provoque des erreurs. La home page de l'application ne s'ouvre pas.

* [Update] Après avoir lu le wiki, je trouve la documentation de config pour WildFly. L'application fonctionne.

## A améliorer

* Compléter votre readme pour faciliter la prise en main de votre projet
    * procédure de mise en place de la db et sa connection
    * configuration minimale pour garantir un premier lancement sans problème
    * lien vers votre wiki pour la configuration de WildFly dans Intellij

**Comment by dosseggegw1** [comment]
Issue corrigée et terminée selon le retour
