### ISSUE TITLE
[Review] Wiki

### ISSUE THREAD

**Issue by NicolasGlassey** [dosseggegw1/AMT_projet#56]
# Wiki (Evaluation 8 sur 10)

Voilà qui change du Readme. De toute évidence vous vous êtes concentré-e-s sur le wiki.

Excellente qualité. Les documents sont à jour, on y voit très bien toutes les étapes et découvertes des technologies.

Cela démontre un très bon suivi dans votre projet. Votre wiki est certainement l'un des plus mieux rédigésdans ce module. Félicitations !

## En bref, par page de wiki

* Accès SSH - ok

* JBoos Wildlfy
    * La configuration avec Tomcat ne permet pas de lancer l'application. Seconde tentative avec Wildfly... le site s'affiche !

* Choix des technologies - ok

* Compte admin - ok

* Construction de routes - ok

* Convention de nommage et git flow - ajouter les liens sources

* Hibernate - très bonne documentation (justification en exemple de jpa)

* Installation serveur applicatif - ok

* JPA Annotation - ok

* Liaison Wildly et MySQL - arrêtez avec votre histoire de root pour MySQL !!! ;)

* Notes - ok

* Organisation - ok

* Retrospective - il est temps d'en écrire une seconde !

* Sécurisation des données - ok

## A améliorer (en plus)

* il me semble que cela ferait plus de sens d'avoir deux axes principaux dans votre wiki.
  * l'un qui mentionnne le paramètrage nécessaire pour collaborer avec vous sur le projet (documentation technique de projet).
  * l'un qui est un cumul de votre prise d'expérience et prise en main des technologies (base de connaissances).

**Comment by dosseggegw1** [comment]
- [x] Convention de nommage et git flow (ajout source ok, uniquement gitflow)
- [x] Liaison wildfly - mysql 
- [x] Retrospective (2e choix ok)
