### ISSUE TITLE
[Review] Clean code

### ISSUE THREAD

**Issue by NicolasGlassey** [dosseggegw1/AMT_projet#60]
# Clean code (Evaluation de 3 à 5)

* Votre code se lit très bien, très soigné. Excellent !

* Retirez les codes désactivés (commentés) avant la review.

* Plusieurs exceptions personnalisées - excellent

* Utilisation de JPA, d'Hibernate... un gros travail d'acquisition de technologies !

## A améliorer

* Retirez les import inutiles (//TODO NGY Remove import statement unused)

* Ajoutez la documentation sur les méthodes publiques !

**Comment by CassandreWoj** [comment]
- [ ] Factorisation "cart"
- [ ] Documentation méthodes publiques
- [ ] Check "//TODO NGY Remove import statement unused"

**Comment by CassandreWoj** [comment]
Imports inutiles retirés et documentation ajoutée sur les méthodes publiques.
