### ISSUE TITLE
[Review] Architecture

### ISSUE THREAD

**Issue by NicolasGlassey** [dosseggegw1/AMT_projet#61]
# Architecture (Evaluation de 2 à 3)

* Mise en place d'une interface DAO - excellent

* Plusieurs méthodes présentes du code totalement identique. Il est temps de refactoriser (//TODO NGY duplicate code fragment)

* Les répertoires (structure générale)
   * **model** pourrait être renommé entities ?
   * sinon gros effort de structure. Excellent !

**Comment by Lindwing** [comment]
duplication de code présent dans le loginController et le registerController corriger dans la PR #54

**Comment by CassandreWoj** [comment]
/!\ APRES LE MERGE FINAL /!\
A faire à la fin du projet : 

- [ ] renommage model -> entities
- [ ] packages DAO avec access & entities
